// <auto-generated />
using System;
using ContractEngine.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ContractEngine.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ContractDbContext))]
    [Migration("20260416114932_AddContractTagsAndVersionsTables")]
    partial class AddContractTagsAndVersionsTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContractEngine.Core.Models.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("AutoRenewal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("auto_renewal");

                    b.Property<int?>("AutoRenewalPeriodMonths")
                        .HasColumnType("integer")
                        .HasColumnName("auto_renewal_period_months");

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("contract_type");

                    b.Property<Guid>("CounterpartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("counterparty_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(3)")
                        .HasDefaultValue("USD")
                        .HasColumnName("currency");

                    b.Property<int>("CurrentVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("current_version");

                    b.Property<DateOnly?>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("GoverningLaw")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("governing_law");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("RagDocumentId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("rag_document_id");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("reference_number");

                    b.Property<int>("RenewalNoticeDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(90)
                        .HasColumnName("renewal_notice_days");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("title");

                    b.Property<decimal?>("TotalValue")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("total_value");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("CounterpartyId");

                    b.HasIndex("TenantId", "CounterpartyId")
                        .HasDatabaseName("ix_contracts_tenant_id_counterparty_id");

                    b.HasIndex("TenantId", "EndDate")
                        .HasDatabaseName("ix_contracts_tenant_id_end_date");

                    b.HasIndex("TenantId", "ReferenceNumber")
                        .HasDatabaseName("ix_contracts_tenant_id_reference_number");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_contracts_tenant_id_status");

                    b.ToTable("contracts", (string)null);
                });

            modelBuilder.Entity("ContractEngine.Core.Models.ContractDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("file_path");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("MimeType")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("mime_type");

                    b.Property<string>("RagDocumentId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("rag_document_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UploadedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("uploaded_by");

                    b.Property<int?>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("TenantId", "ContractId")
                        .HasDatabaseName("ix_contract_documents_tenant_id_contract_id");

                    b.ToTable("contract_documents", (string)null);
                });

            modelBuilder.Entity("ContractEngine.Core.Models.ContractTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tag");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("TenantId", "Tag")
                        .HasDatabaseName("ix_contract_tags_tenant_id_tag");

                    b.HasIndex("TenantId", "ContractId", "Tag")
                        .IsUnique()
                        .HasDatabaseName("ux_contract_tags_tenant_id_contract_id_tag");

                    b.ToTable("contract_tags", (string)null);
                });

            modelBuilder.Entity("ContractEngine.Core.Models.ContractVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ChangeSummary")
                        .HasColumnType("text")
                        .HasColumnName("change_summary");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("created_by");

                    b.Property<string>("DiffResult")
                        .HasColumnType("jsonb")
                        .HasColumnName("diff_result");

                    b.Property<DateOnly?>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id");

                    b.HasIndex("ContractId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_contract_versions_contract_id_version_number");

                    b.HasIndex("TenantId", "ContractId", "VersionNumber")
                        .HasDatabaseName("ix_contract_versions_tenant_id_contract_id_version_number");

                    b.ToTable("contract_versions", (string)null);
                });

            modelBuilder.Entity("ContractEngine.Core.Models.Counterparty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactName")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("contact_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Industry")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("industry");

                    b.Property<string>("LegalName")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("legal_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .HasDatabaseName("ix_counterparties_tenant_id_name");

                    b.ToTable("counterparties", (string)null);
                });

            modelBuilder.Entity("ContractEngine.Core.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasColumnType("varchar(512)")
                        .HasColumnName("api_key_hash");

                    b.Property<string>("ApiKeyPrefix")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("api_key_prefix");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(3)")
                        .HasDefaultValue("USD")
                        .HasColumnName("default_currency");

                    b.Property<string>("DefaultTimezone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("UTC")
                        .HasColumnName("default_timezone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyHash")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_api_key_hash");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("ContractEngine.Core.Models.Contract", b =>
                {
                    b.HasOne("ContractEngine.Core.Models.Counterparty", null)
                        .WithMany()
                        .HasForeignKey("CounterpartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ContractEngine.Core.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContractEngine.Core.Models.ContractDocument", b =>
                {
                    b.HasOne("ContractEngine.Core.Models.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContractEngine.Core.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContractEngine.Core.Models.ContractTag", b =>
                {
                    b.HasOne("ContractEngine.Core.Models.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContractEngine.Core.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContractEngine.Core.Models.ContractVersion", b =>
                {
                    b.HasOne("ContractEngine.Core.Models.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContractEngine.Core.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContractEngine.Core.Models.Counterparty", b =>
                {
                    b.HasOne("ContractEngine.Core.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
