// <auto-generated />
using System;
using ContractEngine.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ContractEngine.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ContractDbContext))]
    partial class ContractDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContractEngine.Core.Models.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("AutoRenewal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("auto_renewal");

                    b.Property<int?>("AutoRenewalPeriodMonths")
                        .HasColumnType("integer")
                        .HasColumnName("auto_renewal_period_months");

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("contract_type");

                    b.Property<Guid>("CounterpartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("counterparty_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(3)")
                        .HasDefaultValue("USD")
                        .HasColumnName("currency");

                    b.Property<int>("CurrentVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("current_version");

                    b.Property<DateOnly?>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("GoverningLaw")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("governing_law");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("RagDocumentId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("rag_document_id");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("reference_number");

                    b.Property<int>("RenewalNoticeDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(90)
                        .HasColumnName("renewal_notice_days");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("title");

                    b.Property<decimal?>("TotalValue")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("total_value");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("CounterpartyId");

                    b.HasIndex("TenantId", "CounterpartyId")
                        .HasDatabaseName("ix_contracts_tenant_id_counterparty_id");

                    b.HasIndex("TenantId", "EndDate")
                        .HasDatabaseName("ix_contracts_tenant_id_end_date");

                    b.HasIndex("TenantId", "ReferenceNumber")
                        .HasDatabaseName("ix_contracts_tenant_id_reference_number");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_contracts_tenant_id_status");

                    b.ToTable("contracts", (string)null);
                });

            modelBuilder.Entity("ContractEngine.Core.Models.ContractDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("file_path");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("MimeType")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("mime_type");

                    b.Property<string>("RagDocumentId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("rag_document_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UploadedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("uploaded_by");

                    b.Property<int?>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("TenantId", "ContractId")
                        .HasDatabaseName("ix_contract_documents_tenant_id_contract_id");

                    b.ToTable("contract_documents", (string)null);
                });

            modelBuilder.Entity("ContractEngine.Core.Models.ContractTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tag");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("TenantId", "Tag")
                        .HasDatabaseName("ix_contract_tags_tenant_id_tag");

                    b.HasIndex("TenantId", "ContractId", "Tag")
                        .IsUnique()
                        .HasDatabaseName("ux_contract_tags_tenant_id_contract_id_tag");

                    b.ToTable("contract_tags", (string)null);
                });

            modelBuilder.Entity("ContractEngine.Core.Models.ContractVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ChangeSummary")
                        .HasColumnType("text")
                        .HasColumnName("change_summary");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("created_by");

                    b.Property<string>("DiffResult")
                        .HasColumnType("jsonb")
                        .HasColumnName("diff_result");

                    b.Property<DateOnly?>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id");

                    b.HasIndex("ContractId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_contract_versions_contract_id_version_number");

                    b.HasIndex("TenantId", "ContractId", "VersionNumber")
                        .HasDatabaseName("ix_contract_versions_tenant_id_contract_id_version_number");

                    b.ToTable("contract_versions", (string)null);
                });

            modelBuilder.Entity("ContractEngine.Core.Models.Counterparty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactName")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("contact_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Industry")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("industry");

                    b.Property<string>("LegalName")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("legal_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .HasDatabaseName("ix_counterparties_tenant_id_name");

                    b.ToTable("counterparties", (string)null);
                });

            modelBuilder.Entity("ContractEngine.Core.Models.DeadlineAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Acknowledged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("acknowledged");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("acknowledged_at");

                    b.Property<string>("AcknowledgedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("acknowledged_by");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("alert_type");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("DaysRemaining")
                        .HasColumnType("integer")
                        .HasColumnName("days_remaining");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<bool>("NotificationSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("notification_sent");

                    b.Property<DateTime?>("NotificationSentAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("notification_sent_at");

                    b.Property<Guid>("ObligationId")
                        .HasColumnType("uuid")
                        .HasColumnName("obligation_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("ObligationId");

                    b.HasIndex("TenantId", "ObligationId")
                        .HasDatabaseName("ix_deadline_alerts_tenant_id_obligation_id");

                    b.HasIndex("TenantId", "Acknowledged", "CreatedAt")
                        .HasDatabaseName("ix_deadline_alerts_tenant_id_acknowledged_created_at");

                    b.ToTable("deadline_alerts", (string)null);
                });

            modelBuilder.Entity("ContractEngine.Core.Models.ExtractionJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<int>("ObligationsConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("obligations_confirmed");

                    b.Property<int>("ObligationsFound")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("obligations_found");

                    b.Property<string[]>("PromptTypes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("prompt_types");

                    b.Property<string>("RagDocumentId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("rag_document_id");

                    b.Property<string>("RawResponses")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_responses");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("queued")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("TenantId", "ContractId")
                        .HasDatabaseName("ix_extraction_jobs_tenant_id_contract_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_extraction_jobs_tenant_id_status");

                    b.ToTable("extraction_jobs", (string)null);
                });

            modelBuilder.Entity("ContractEngine.Core.Models.ExtractionPrompt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PromptText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt_text");

                    b.Property<string>("PromptType")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("prompt_type");

                    b.Property<string>("ResponseSchema")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_schema");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "PromptType")
                        .IsUnique()
                        .HasDatabaseName("ux_extraction_prompts_tenant_id_prompt_type");

                    b.ToTable("extraction_prompts", (string)null);
                });

            modelBuilder.Entity("ContractEngine.Core.Models.HolidayCalendar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CalendarCode")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("calendar_code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("HolidayDate")
                        .HasColumnType("date")
                        .HasColumnName("holiday_date");

                    b.Property<string>("HolidayName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("holiday_name");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CalendarCode")
                        .HasDatabaseName("ix_holiday_calendars_tenant_id_calendar_code");

                    b.HasIndex("CalendarCode", "Year", "HolidayDate")
                        .HasDatabaseName("ix_holiday_calendars_calendar_code_year_holiday_date");

                    b.HasIndex("TenantId", "CalendarCode", "HolidayDate")
                        .IsUnique()
                        .HasDatabaseName("ux_holiday_calendars_tenant_id_calendar_code_holiday_date");

                    b.ToTable("holiday_calendars", (string)null);
                });

            modelBuilder.Entity("ContractEngine.Core.Models.Obligation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AlertWindowDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30)
                        .HasColumnName("alert_window_days");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("amount");

                    b.Property<string>("BusinessDayCalendar")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("US")
                        .HasColumnName("business_day_calendar");

                    b.Property<string>("ClauseReference")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("clause_reference");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("confidence_score");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(3)")
                        .HasDefaultValue("USD")
                        .HasColumnName("currency");

                    b.Property<DateOnly?>("DeadlineDate")
                        .HasColumnType("date")
                        .HasColumnName("deadline_date");

                    b.Property<string>("DeadlineFormula")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("deadline_formula");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("ExtractionJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("extraction_job_id");

                    b.Property<int>("GracePeriodDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("grace_period_days");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<DateOnly?>("NextDueDate")
                        .HasColumnType("date")
                        .HasColumnName("next_due_date");

                    b.Property<string>("ObligationType")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("obligation_type");

                    b.Property<string>("Recurrence")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("recurrence");

                    b.Property<string>("ResponsibleParty")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("us")
                        .HasColumnName("responsible_party");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("manual")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("TenantId", "ContractId")
                        .HasDatabaseName("ix_obligations_tenant_id_contract_id");

                    b.HasIndex("TenantId", "NextDueDate")
                        .HasDatabaseName("ix_obligations_tenant_id_next_due_date");

                    b.HasIndex("TenantId", "ObligationType")
                        .HasDatabaseName("ix_obligations_tenant_id_obligation_type");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_obligations_tenant_id_status");

                    b.ToTable("obligations", (string)null);
                });

            modelBuilder.Entity("ContractEngine.Core.Models.ObligationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("actor");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("from_status");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<Guid>("ObligationId")
                        .HasColumnType("uuid")
                        .HasColumnName("obligation_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("to_status");

                    b.HasKey("Id");

                    b.HasIndex("ObligationId");

                    b.HasIndex("TenantId", "ObligationId", "CreatedAt")
                        .HasDatabaseName("ix_obligation_events_tenant_id_obligation_id_created_at");

                    b.ToTable("obligation_events", (string)null);
                });

            modelBuilder.Entity("ContractEngine.Core.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasColumnType("varchar(512)")
                        .HasColumnName("api_key_hash");

                    b.Property<string>("ApiKeyPrefix")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("api_key_prefix");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(3)")
                        .HasDefaultValue("USD")
                        .HasColumnName("default_currency");

                    b.Property<string>("DefaultTimezone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("UTC")
                        .HasColumnName("default_timezone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyHash")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_api_key_hash");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("ContractEngine.Core.Models.Contract", b =>
                {
                    b.HasOne("ContractEngine.Core.Models.Counterparty", null)
                        .WithMany()
                        .HasForeignKey("CounterpartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ContractEngine.Core.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContractEngine.Core.Models.ContractDocument", b =>
                {
                    b.HasOne("ContractEngine.Core.Models.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContractEngine.Core.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContractEngine.Core.Models.ContractTag", b =>
                {
                    b.HasOne("ContractEngine.Core.Models.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContractEngine.Core.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContractEngine.Core.Models.ContractVersion", b =>
                {
                    b.HasOne("ContractEngine.Core.Models.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContractEngine.Core.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContractEngine.Core.Models.Counterparty", b =>
                {
                    b.HasOne("ContractEngine.Core.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContractEngine.Core.Models.DeadlineAlert", b =>
                {
                    b.HasOne("ContractEngine.Core.Models.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ContractEngine.Core.Models.Obligation", null)
                        .WithMany()
                        .HasForeignKey("ObligationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ContractEngine.Core.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContractEngine.Core.Models.ExtractionJob", b =>
                {
                    b.HasOne("ContractEngine.Core.Models.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ContractEngine.Core.Models.ContractDocument", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ContractEngine.Core.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContractEngine.Core.Models.ExtractionPrompt", b =>
                {
                    b.HasOne("ContractEngine.Core.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ContractEngine.Core.Models.HolidayCalendar", b =>
                {
                    b.HasOne("ContractEngine.Core.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ContractEngine.Core.Models.Obligation", b =>
                {
                    b.HasOne("ContractEngine.Core.Models.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ContractEngine.Core.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContractEngine.Core.Models.ObligationEvent", b =>
                {
                    b.HasOne("ContractEngine.Core.Models.Obligation", null)
                        .WithMany()
                        .HasForeignKey("ObligationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContractEngine.Core.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
