using ContractEngine.Core.Abstractions;
using ContractEngine.Core.Enums;
using ContractEngine.Core.Pagination;

namespace ContractEngine.Core.Models;

/// <summary>
/// DeadlineAlert — a single alert generated by the Deadline Scanner (Batch 016) or the Contract
/// Analysis engine (Phase 2). PRD §4.9.
///
/// <para>Idempotency: the <c>DeadlineAlertService.CreateIfNotExistsAsync</c> pipeline enforces a
/// logical UNIQUE on <c>(obligation_id, alert_type, days_remaining)</c> so re-running the scanner
/// within the same window never duplicates a row. The DB does not carry a matching UNIQUE index —
/// the uniqueness contract is application-level so the scanner can coexist with backfill scripts
/// that deliberately clone alerts for testing.</para>
///
/// <para>Tenant isolation: implements <see cref="ITenantScoped"/>. Pagination: implements
/// <see cref="IHasCursor"/> so <c>GET /api/alerts</c> uses the shared <c>(CreatedAt, Id)</c>
/// cursor helper. FKs to <see cref="Obligation"/> and <see cref="Contract"/> use
/// <c>DeleteBehavior.Restrict</c> — an alert row is audit/notification history and MUST survive
/// its parent obligation going terminal; production never hard-deletes obligations, but the guard
/// catches seed-cleanup accidents loudly.</para>
/// </summary>
public class DeadlineAlert : ITenantScoped, IHasCursor
{
    public Guid Id { get; set; }

    public Guid TenantId { get; set; }

    public Guid ObligationId { get; set; }

    /// <summary>
    /// Denormalised from <see cref="Obligation.ContractId"/> so "alerts for this contract"
    /// lookups avoid a join. Kept in sync at creation time — obligations don't switch contracts.
    /// </summary>
    public Guid ContractId { get; set; }

    public AlertType AlertType { get; set; }

    /// <summary>
    /// Business days remaining at creation time. Nullable because overdue / conflict alerts don't
    /// carry a forward-looking horizon (the value at issue is already in the past).
    /// </summary>
    public int? DaysRemaining { get; set; }

    public string Message { get; set; } = string.Empty;

    public bool Acknowledged { get; set; }

    public DateTime? AcknowledgedAt { get; set; }

    public string? AcknowledgedBy { get; set; }

    /// <summary>
    /// Set by the downstream Notification Hub dispatcher (Phase 3). Stays <c>false</c> throughout
    /// Batch 015 — the endpoint layer never flips it; the scanner / dispatch job owns that.
    /// </summary>
    public bool NotificationSent { get; set; }

    public DateTime? NotificationSentAt { get; set; }

    public DateTime CreatedAt { get; set; }
}
